import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DefaultLayout from './components/layout'
import { useEffect } from 'react'
import { App, ConfigProvider } from 'antd'
import zhCN from 'antd/locale/zh_CN';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NAStool-react',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="zh">
      <body className={inter.className}>
        <ConfigProvider locale={zhCN}>
          <App>
            <DefaultLayout>{children}</DefaultLayout>
          </App>
        </ConfigProvider>
      </body>
    </html>
  )
}
